name: Load Test - Nightly

on:
  workflow_dispatch:
    inputs:
        scenarios:
            description: 'Scenarios to run'
            required: false
            default: 'h1-h1,h1c-h1c,h2c-h2c,h2-h2'
            type: string
        payloads:
            description: 'Payloads to run'
            required: false
            default: '500B,1000B,10000B'
            type: string
        users:
            description: 'Users to run'
            required: false
            default: '100,200,500,1000'
            type: string
        duration:
            description: 'Duration of the test'
            required: false
            default: '1h'
            type: string
        distribution-url:
            description: 'URL of the Ballerina distribution'
            required: false
            type: string
        ballerina-path:
            description: 'Path to the Ballerina command'
            required: false
            type: string
jobs:
    load-tests:
        name: Run Load Tests
        runs-on: ubuntu-latest
        timeout-minutes: 540
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Java 21
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: Setup Ballerina
              if: ${{ github.event.inputs.distribution-url != null && github.event.inputs.ballerina-path != null }}
              uses: ballerina-platform/setup-ballerina@v1.1.3
              with:
                version: nightly

            - name: Setup Ballerina from provided URL
              if: ${{ github.event.inputs.distribution-url != null && github.event.inputs.ballerina-path != null }}
              run: |
                wget ${{ github.event.inputs.distribution-url }} -O ballerina.zip
                unzip ballerina.zip
                export PATH=$PWD/${{ github.event.inputs.ballerina-path }}:$PATH
                bal --version
            
            - name: Setup h2load
              run: |
                sudo apt-get update
                sudo apt-get install -y nghttp2-client

            - name: Build backend and Ballerina services
              run: bash ./scripts/build.sh
              env:
                BALLERINA_PROJECTS: ${{ github.event.inputs.scenarios }}

            - name: Run Load Tests
              run: bash ./scripts/load_test.sh
              env:
                SCENARIOS: ${{ github.event.inputs.scenarios }}
                PAYLOADS: ${{ github.event.inputs.payloads }}
                CONCURRENCY: ${{ github.event.inputs.users }}
                LOAD_TEST_DURATION: ${{ github.event.inputs.duration }}

            - name: Create report
              run: bash ./scripts/report.sh

            - name: Print the report as summary
              run: cat report.md >> $GITHUB_STEP_SUMMARY

