name: On demand build without tests

on:
  workflow_dispatch:
    inputs:
        scenarios:
            description: 'Scenarios to run'
            required: false
            default: '("h1-h1" "h1c-h1c" "h1-h2" "h2-h1" "h1c-h2c" "h2c-h1c" "h2c-h2c" "h2-h2")'
            type: string
        payloads:
            description: 'Payloads to run'
            required: false
            default: '("500B" "1000B" "10000B")'
            type: string
        users:
            description: 'Users to run'
            required: false
            default: '(100 200 500 1000)'
            type: string
jobs:
    load-tests:
        name: Run Load Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Java 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Setup Ballerina
              uses: ballerina-platform/setup-ballerina@v1.1.3
              with:
                version: 2201.10.3

            
            - name: Setup h2load
              run: |
                sudo apt-get update
                sudo apt-get install -y nghttp2-client

            - name: Build backend and Ballerina services
              run: sh ./scripts/build.sh

            - name: Run Load Tests
              run: sh ./scripts/load_test.sh
              env:
                SCENARIOS: ${{ github.event.inputs.scenarios }}
                PAYLOADS: ${{ github.event.inputs.payloads }}
                USERS: ${{ github.event.inputs.users }}

            - name: Create report
              run: sh ./scripts/report.sh

            - name: Print the report as summary
              run: cat report.md >> $GITHUB_STEP_SUMMARY

