name: Trigger Load Test

on:
  workflow_dispatch:
    inputs:
      ballerina-version:
        description: 'Ballerina version to use'
        required: false
        default: 'nightly'
        type: string
      java-version:
        description: 'Java version to use'
        required: false
        type: string
      scenarios:
        description: 'Scenarios to run'
        required: false
        default: '["h1-h1","h1c-h1c","h2c-h2c","h2-h2"]'
        type: string
      payloads:
        description: 'Payloads to run'
        required: false
        default: '500B,1000B,10000B'
        type: string
      users:
        description: 'Users to run'
        required: false
        default: '100,200,500,1000'
        type: string
      duration:
        description: 'Duration of the test'
        required: false
        default: '1h'
        type: string
      zipURL:
        description: 'URL of the Ballerina distribution'
        required: false
        type: string
      ballerina-path:
        description: 'Path to the Ballerina command'
        required: false
        default: 'ballerina-dist/bin'
        type: string
jobs:
  load-test:
    name: Run Load Test
    runs-on: ubuntu-latest
    timeout-minutes: 540
    strategy:
      matrix:
        scenario: ${{ fromJSON(github.event.inputs.scenarios) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ballerina
        if: ${{ github.event.inputs.zipURL == null && github.event.inputs.ballerina-path == null }}
        uses: ballerina-platform/setup-ballerina@v1.1.3
        with:
          version: ${{ github.event.inputs.ballerina-version }}

      - name: Setup Ballerina from provided URL
        if: ${{ github.event.inputs.zipURL != null && github.event.inputs.ballerina-path != null }}
        run: |
          curl -u TharmiganK:${{ secrets.TOKEN }} -L -o ballerina-dist.zip ${{ github.event.inputs.zipURL }}
          unzip -q ballerina-dist.zip -d ballerina-dist
          chmod +x $PWD/${{ github.event.inputs.ballerina-path }}/bal
          echo PATH=$PWD/${{ github.event.inputs.ballerina-path }}:$PATH >> $GITHUB_ENV

      - name: Check Ballerina version and determine Java version
        if: ${{ github.event.inputs.java-version == null }}
        run: |
          BAL_VERSION=$(bal --version | awk '/Ballerina / {print $2}')
          JAVA_VERSION=$(echo $BAL_VERSION | awk -F'.' '{print ($2 >= 11) ? 21 : 17}') 
          echo JAVA_VERSION=$JAVA_VERSION >> $GITHUB_ENV
          echo "Using Java $JAVA_VERSION for Ballerina $BAL_VERSION"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ github.event.inputs.java-version || env.JAVA_VERSION }}'

      - name: Setup h2load
        run: |
          sudo apt-get update
          sudo apt-get install -y nghttp2-client

      - name: Build backend and Ballerina services
        run: bash ./scripts/build.sh
        env:
          BALLERINA_PROJECTS: ${{ matrix.scenario }}

      - name: Run Load Test
        run: bash ./scripts/load_test.sh
        env:
          SCENARIOS: ${{ matrix.scenario }}
          PAYLOADS: ${{ github.event.inputs.payloads }}
          CONCURRENCY: ${{ github.event.inputs.users }}
          LOAD_TEST_DURATION: ${{ github.event.inputs.duration }}

      - name: Create report
        run: bash ./scripts/report.sh

      - name: Print the report as summary
        run: cat report.md >> $GITHUB_STEP_SUMMARY
